### ISSUE TITLE
Update to Set 8.5

### ISSUE THREAD

**Issue by Gadsee** [Kyrluckechuck/TFT-Bot#100]
To-Do tracking issue
Also, update the GitHub project description to say 8.5 instead of 7.5
Also, maybe reconsider `wanted_traits.` Laser corps is underperforming with the removed units (IMO). Duelists look promising for the curve we're going for.

**Comment by Kyrluckechuck** [comment]
I'm not sure I understand what you mean by `To-Do tracking issue`? 🤔 

>  Also, update the GitHub project description to say 8.5 instead of 7.5
Yep, good call!

>  Also, maybe reconsider wanted_traits. Laser corps is underperforming with the removed units (IMO). Duelists look promising for the curve we're going for.

That makes sense! I've been noticing that lately myself. Lasercorps used to scale well into mid to late game, but now it is only strong early game and even then not enough compared to Duelists 👌

**Comment by Kyrluckechuck** [comment]
Ahh I understand, I was misreading that 👌
