### ISSUE TITLE
Move to Semantic Versioning of Releases

### ISSUE THREAD

**Issue by Kyrluckechuck** [Kyrluckechuck/TFT-Bot#116]
## Description

Right now releases are tagged with their commit, which is auto-generated and appears to cause the releases to be out of order if there are multiple releases on the same day (since it's appear to sort alphabetically by tag, not by release title or date).

I had tried to avoid adding a file/config specifically specifying the version, but it looks like this may not be possible -- if others have a better/cleaner suggestion, I am open to it!

To be clear the releases are technically following that, but the tags they use are not.

**Comment by Gadsee** [comment]
I know this adds more than just a file, but I'd love to see this done with the help of [poetry](https://python-poetry.org/) and an action script (i.e., https://github.com/marketplace/actions/release-poetry-python-project or https://gist.github.com/joshuakraitberg/472bb5911d358eb18b0264d1bd953e66, I'm sure there are more iterations of this out there).
Just throwing the idea into the ring :)

**Comment by Kyrluckechuck** [comment]
Hmm, that's definitely a different idea!

I hadn't heard of the Poetry package before, and while it seems need, it honestly seems a bit overkill since the project has such simple dependencies? Again not against it, though 😛 

Those commit workflows seem to be more geared towards building & publishing to PyPI, which I'm not strictly against, but also was not explicitly looking to add 🤔

**Comment by Gadsee** [comment]
The `poetry publish` step is aimed towards packages, but as seen in the links above, it is possible to "kind of" integrate it with GitHub releases. The main benefit I was considering here in the scope of this issue is its capability of [version bumping](https://python-poetry.org/docs/cli/#version) (but also plain defining if you prefer).

I could get into great detail as to how much I love poetry, but the TL;DR is that it makes setting up venvs, but especially adding, removing, and upgrading packages so trivial. I totally understand if it's a bit much for now, though!

**Comment by Kyrluckechuck** [comment]
Haha that's enough to sell me -- I'll be honest that I don't have a ton of time to dive into this myself for now, so if you've got a strong grasp on it and are able to get an initial PR up, I'm happy to take a peek! I'm not sure if that will work with a forked repo properly or if you will have to submit the via a branch on this repo just due to the nature of how CI works, but if you don't mind attribution getting messed up I can copy it over after (I don't love that, but I'd prefer to test it successfully in CI if it's not running on the other forks properly before merging it)

**Comment by Gadsee** [comment]
I'm confident in my poetry but my DevOps skills are mainly in GitLab, so I'll have to struggle a bit with actions to tell you if I can make a PR. Am totally down to give it a shot though!

**Comment by Kyrluckechuck** [comment]
Totally fair! I can try to spend a bit of time tomorrow looking into this, I'll take a stab and see if I can figure it out in a timely manor 😛
