### ISSUE TITLE
Game Does Not End After Being Eliminated

### ISSUE THREAD

**Issue by Jokiblack** [Kyrluckechuck/TFT-Bot#118]
i have game in english
![image](https://user-images.githubusercontent.com/8556969/229641832-a9456e28-242c-48eb-963f-170dd45cfb8a.png)

![image](https://user-images.githubusercontent.com/8556969/229641725-0955601d-f083-4e85-a837-ed2aa5ffc160.png)

**Comment by Gadsee** [comment]
Hmm, it is weird that it is not finding this
![exit_now_base](https://user-images.githubusercontent.com/60011425/229643610-b9e70bf3-d50f-48d7-8afb-bc3557b144d1.png)
image. Could you attach the log, just in case? (It's in your `%appdata%\tft bot` folder.)

 Also, out of curiosity, since you didn't re-open the other issue, did it click the button?

**Comment by Jokiblack** [comment]
> Hmm, it is weird that it is not finding this ![exit_now_base](https://user-images.githubusercontent.com/60011425/229643610-b9e70bf3-d50f-48d7-8afb-bc3557b144d1.png) image. Maybe the font or resolution is a bit off? Could you attach the log, just in case? (It's in your `%appdata%\tft bot` folder.)
> 
> Also, out of curiosity, since you didn't re-open the other issue, did it click the button?

I'm not used to using this website to report bugs, so I didn't reopen the other issue

no log file was generated in that folder when closing the program the folder was deleted

**Comment by Kyrluckechuck** [comment]
Ah, this was probably the version before that updated back to using the appdata folder -- the log file would be in the directory where the executable was stored, probably your downloads folder?

**Comment by Jokiblack** [comment]
![image](https://user-images.githubusercontent.com/8556969/229646420-f81ef8c9-6955-485c-9c95-bcac24334b5a.png)

**Comment by Gadsee** [comment]
Could you post a screenshot of your **entire** screen that has League on it when this is happening? I have a feeling it might be the resolution.

**Comment by Jokiblack** [comment]
Everything works, it is in a virtual machine at 1080 always, only this option does not work, the rest everything is perfect, it takes more than 48 hours

**Comment by Kyrluckechuck** [comment]
.. it takes more than 48 hours? Is your machine locking up or something? The game will auto-exit on its own after the game ends / 1st place is earned by someone😕

**Comment by Jokiblack** [comment]
> .. it takes more than 48 hours? Is your machine locking up or something? The game will auto-exit on its own after the game ends / 1st place is earned by someone (without the bot, even) 😕
Yes of course, close the game when the last one dies
![image](https://user-images.githubusercontent.com/8556969/229707990-04850736-001c-40eb-afb3-8490d212282d.png)

**Comment by Jokiblack** [comment]
![image](https://user-images.githubusercontent.com/8556969/229830113-5aaa694e-aa68-4256-a87b-5b32eb3295f8.png)

**Comment by Gadsee** [comment]
Yup, that's what I expect to happen at the moment, the client completely restarting if we're still in-game after trying to click on the exit now button.
I'm working on a more graceful solution than this, but it's a bit annoying to exit out of a game without clicking the button, so it's taking a whole lot of debugging 🥲

**Comment by Kyrluckechuck** [comment]
Interesting -- it looks like your process doesn't have access to kill a process (which is what it was attempting to do there but raised an exception). Are you running on a limited user account by chance that does not have admin access?

**Comment by Jokiblack** [comment]
It is the only profile that exists in the virtual machine, I am going to start the bot in admin and I will tell you

**Comment by Kyrluckechuck** [comment]
@Jokiblack oh, that is very odd then 🤔 

I wouldn't think you'd need to actually run it as an administrator, but do let us know if that changes the behaviour at all for you!

**Comment by Jokiblack** [comment]
> @Jokiblack oh, that is very odd then 🤔
> 
> I wouldn't think you'd need to actually run it as an administrator, but do let us know if that changes the behaviour at all for you!

still can't find the button and doesn't close

![image](https://user-images.githubusercontent.com/8556969/229847829-f59e9225-233c-44b8-be7d-5901eb275632.png)

**Comment by Jokiblack** [comment]
yep close game
![image](https://user-images.githubusercontent.com/8556969/229853702-68924627-effd-46a6-92c0-ab24722a0ab8.png)

**Comment by Gadsee** [comment]
Hey @Jokiblack , could you try the latest release (https://github.com/Kyrluckechuck/TFT-Bot/releases/tag/v0.11.4.6) after the above merge?

**Comment by Jokiblack** [comment]
![image](https://user-images.githubusercontent.com/8556969/230005172-5b1ba0e6-0929-4145-a620-c515627f59a8.png)
![image](https://user-images.githubusercontent.com/8556969/230005330-66dcef5c-1499-42ca-890a-ac6bb5da0dc1.png)
no exit

> Hey @Jokiblack , could you try the latest release (https://github.com/Kyrluckechuck/TFT-Bot/releases/tag/v0.11.4.7) after the above merge?

**Comment by Jokiblack** [comment]
in new version dont buy xp, and no exit

**Comment by Gadsee** [comment]
Please attach the latest debug log (should be in `%APPDATA%\TFT Bot`)

**Comment by Gadsee** [comment]
Also, your resolution is 1920x972, which probably is the reason for the font on the exit button being squished and not being recognized by the bot. Since you're running a VM, I assume the rest of the pixels is the host's task bar preventing your VM window from expanding to 1080.

**Comment by Jokiblack** [comment]
> reventing your VM

lol is in 1080 all time

**Comment by Gadsee** [comment]
Your screenshot says it's 972 ^^ I somehow doubt that it's resizing just for the action of you taking a screenshot, but I can only tell you what I can see, not what's actually the case.

Anyway, I still need the debug log to see the reason why the process could not be terminated.

**Comment by Jokiblack** [comment]
I am reinstalling the machine to see why it may be that of the resolution

**Comment by Kyrluckechuck** [comment]
In the screenshot that show the desktop tray bar, I noticed a few things:
1. The task bar / tray bar is visible and showing over the game client -- is that just in the screenshot or is that what it looks like when it's running, too?
2. There's a tiny chance the `Activate Windows` text in the bottom right of the screen is impacting the ability to correctly read the images on the screen. That should really not affect anything I can think of, but just something I noticed that _could_ be related.
3. The screen resolution of one of the images you uploaded is `1922x973` -- is that a full screen screenshot, or are you sub-selecting most of the screen as a screenshot?

You mention a VM, what hypervisor are you running it in? Windows Hyper-V / VMware / Virtualbox / QEMU / Something else altogether? You may need to update the settings for whichever hypervisor you're using to keep a constant screen resolution of `1920x1080` instead of 'dynamic'/'resizable'
