### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Vermax104** [Kyrluckechuck/TFT-Bot#127]
Hi, I'm having a problem with the installation, I don't have any programming knowledge, I'm following the steps, but there's this problem that I can't solve...
[log.txt](https://github.com/Kyrluckechuck/TFT-Bot/files/11185921/log.txt)

**Comment by Gadsee** [comment]
It could be that the error occurs because the `output` folder does not exist, could you create it manually and see if that solves it?

**Comment by Vermax104** [comment]
thank you very much for clarifying this to me, the bot is on, but there is another problem, maybe it's because of my resolution (1440x900), any solutions?
[log.txt](https://github.com/Kyrluckechuck/TFT-Bot/files/11186156/log.txt)
