### ISSUE TITLE
"can't open/read file: check file path/integrity"

### ISSUE THREAD

**Issue by Vermax104** [Kyrluckechuck/TFT-Bot#129]
O bot está funcionando no lobby, mas in game ele não funciona, acredito que seja por causa da minha resolução (1440x900), alguma solução para isso?
[log.txt](https://github.com/Kyrluckechuck/TFT-Bot/files/11186182/log.txt)

**Comment by Vermax104** [comment]
I double-checked and found that the path specified in the logs is incorrect/badly formatted. the word "├ürea" is incorrect, the correct one is "Área'', how can I change it?

**Comment by Kyrluckechuck** [comment]
Interesting, it looks like the encoding for the file path is struggling with the accented Unicode characters -- as a workaround, you could move it to any directory path which does not contain any special characters.

Also what may be worth noting, is you are launching the bot in what appears to be a cloud-synced folder that may cause some weird behaviour, so just wanted to raise that before you have some wiwed issues! 😛

**Comment by Kyrluckechuck** [comment]
After further debugging, [this Python doc](https://python.readthedocs.io/en/latest/howto/unicode.html#tips-for-writing-unicode-aware-programs) appears highly relevant

**Comment by Kyrluckechuck** [comment]
Further debugging, looks like the actual project is fine and [it's an issue with the `opencv2` library](https://github.com/opencv/opencv/issues/21770) that `python-imagesearch` uses

One potential workaround is to change to the folder that contains the project/temp files in the context of the program, and then execute. I haven't tested this, but not sure how ideal it is 😬 
```python3
import os
os.chdir(folder_address_which_contain_your_file)
```
(via https://github.com/opencv/opencv/issues/21770)

**Comment by Kyrluckechuck** [comment]
@Vermax104 could you try that same folder but using the branch `potential-resource-path-fix`?

**Comment by Kyrluckechuck** [comment]
Since we didn't get a response and the code seemed harmless enough (and it worked in my testing), I've gone ahead and merged it into `main`, and it will be included in the next release. Please reopen this ticket if it has not been resolved.
