### ISSUE TITLE
Change lineup

### ISSUE THREAD

**Issue by DAI-HY** [Kyrluckechuck/TFT-Bot#148]
Hello!  I modified the config file after downloading the code to test the strength of different lineups.  But after I changed the selected lineup it was still duelist and brawler during the test.  Can you please explain where I am doing wrong?

**Comment by Kyrluckechuck** [comment]
Ah, that's definitely no good!

Can you please attach a copy of your config, as well as the logs for the client during a run which did not use the modified config you specified?

**Comment by DAI-HY** [comment]
# The traits you want the bot to roll for.
# The trait names are almost as written in-game, with spaces replaced by _ and . and : being ignored.
# For example: admin, star_guardian, mecha_prime, lasercorps
# For a full list, visit https://github.com/Kyrluckechuck/TFT-Bot/tree/main/captures/trait
wanted_traits:
  - gadeteen
  - hacker

For the config file, I only made changes to this part.

**Comment by Gadsee** [comment]
For your information, I edited your comment to display the config correctly 🙂 

I'm curious: If you're running from the source (You said you "downloaded the code"), are you changing the config in the `%APPDATA%\TFT Bot` or the `output` folder? The first is for the executable file from the release page, and the second is for running from the source.

Another thing, you have a typo in `gadgeteen`, but that should not result in it buying the default traits. (Although we should probably add a fix for that)

**Comment by DAI-HY** [comment]
thank you for your reply.  I think I know how to change it.🥰
