### ISSUE TITLE
Issues Loading Tesseract Config When Using Executable

### ISSUE THREAD

**Issue by Kyrluckechuck** [Kyrluckechuck/TFT-Bot#154]
## Description
Creating an issue from the following discussion:
### Discussed in https://github.com/Kyrluckechuck/TFT-Bot/discussions/153

<div type='discussions-op-text'>

<sup>Originally posted by **Kelthuzer** April 25, 2023</sup>
I can't figure out how to activate it in the bot. there is no mention of this in the settings file

i use .exe, after update the config file is not created by itself and is ignored in %appdata%\tft bot, strings appeared in TFT Bot_MEI****\tft_bot\resources but _mei new each start
</div>

## Action / Followup
@kelthuzer, I'm creating an issue here to better track that since it sounds more like this could be either a configuration issue or a bug in detecting the change.

Could you please reply to this with the logs the bot generated in `%appdata%\TFT Bot`, as well as your configuration file?

**Comment by Gadsee** [comment]
Has been resolved by running the bot as administrator. I'll move the task of checking why the elevator bit we have in the .exe at the moment doesn't work into #157.
