### ISSUE TITLE
Log Output Folder To Console At Bot Startup

### ISSUE THREAD

**Issue by Kyrluckechuck** [Kyrluckechuck/TFT-Bot#157]
## Description
While attempting to help debug the issue discussed in https://github.com/Kyrluckechuck/TFT-Bot/discussions/153, it became apparent that both the output log folder and the config file are not being generated as expected.

Regardless of the issue itself, it seems it would be valuable to output this for the user to know which config is being used, as well as for log file location to help debug issues they may experience.

**Comment by Gadsee** [comment]
Note from the issue linked above, please also check if we have write and read permissions into the output folder. If possible, check why the administrator requirement to run the bot does not seem to automatically give those permissions.
