### ISSUE TITLE
After Match startup the bot doesnt do anything

### ISSUE THREAD

**Issue by Genex7** [Kyrluckechuck/TFT-Bot#160]
After Match startup the bot doesnt do anything, something curious is that when i click on other windows or the CMD the mouse start move automatically but when i click the window of the TFT game , suddenly stops , i check out the output and i saw this :
![image](https://user-images.githubusercontent.com/132827210/236679831-e1f94a91-f4f7-420f-b955-dfca53296deb.png)
please help

**Comment by Gadsee** [comment]
Hey, the bot is missing permission to bring the league window to the forefront. Can you try manually running the bot as administrator, please?

**Comment by Genex7** [comment]
how can i do that?

**Comment by Kyrluckechuck** [comment]
There are many ways. [Windows Central](https://www.windowscentral.com/how-run-app-administrator-windows-10) shows a number of them, but the simplest if you're using the release executable would be to: `Right-click app, and select the Run as administrator option.`

**Comment by Genex7** [comment]
nice that worked, the bot now do the action but i detected another problem, the bot doesnt pick up the items to put on the champions , is that normal ? thank u btw

**Comment by Gadsee** [comment]
Yup, that's normal. We have an open issue (#159) asking for that feature at the moment, but neither of us had the time to look into it yet.
