### ISSUE TITLE
Multiple League Processes Created

### ISSUE THREAD

**Issue by xChickens** [Kyrluckechuck/TFT-Bot#166]
![image](https://github.com/Kyrluckechuck/TFT-Bot/assets/2402510/d1d56fd8-eb8a-4175-8b7a-8e1a8de445b5)
Not sure what happened here... but I checked my task manager and there were a bunch of League of Legends Processes (like 10 or so) with multiple of them in a "suspended" state. The bot seemed to have crashed and there was no way to interact with any League process.

Not sure what went wrong, will be running the bot again tonight so we'll see.

**Comment by xChickens** [comment]
Nevermind, found out that my computer loads the client really slowly, so when the bot launches the client it would just try to exit and reopen a client. Guess I would need to adjust the timeouts or something.

**Comment by Gadsee** [comment]
I've noticed the frequent client restarts as well on my end, but the icons are just "fake", in the sense that hovering over them makes them disappear, so I haven't bothered looking into it. Could you provide your latest log file for us to look into? Your assumption that we're interacting with the client too fast is probably right, but making the bot more robust is always good :)

**Comment by xChickens** [comment]
[tft-bot-debug-2023-05-09_01-22-22_543533.log](https://github.com/Kyrluckechuck/TFT-Bot/files/11461615/tft-bot-debug-2023-05-09_01-22-22_543533.log)

Here's the log (though I'm banned now :/)

**Comment by Kyrluckechuck** [comment]
Unless other users encounter this, I'm going to close this for now since we haven't seen other reports!
