### ISSUE TITLE
The bot doesn't do anything in-game. (except one thing)

### ISSUE THREAD

**Issue by LantiHUN** [Kyrluckechuck/TFT-Bot#179]
Self explanatory. The bot doesn't do anything except selecting the augment offer. Everything seems alright. 

[tft-bot-debug-2023-06-13_15-26-17_958403.log](https://github.com/Kyrluckechuck/TFT-Bot/files/11735586/tft-bot-debug-2023-06-13_15-26-17_958403.log)

**Comment by LantiHUN** [comment]
Note that I have a 2560x1600 monitor, but I reduced the resolution while using the script to FHD. The script was able to select the augment so I don't think that this was the problem. Also I have a second monitor. The script was running on the second monitor and the game was on the main monitor.

**Comment by akshualy** [comment]
Considering a new set came out a few hours ago, I'll prioritize updating the bot before looking into this.
Could you provide a fullscreen screenshot of your league window (feel free to black out/remove any names) so we can double-check the resolution?

**Comment by Kumicoo** [comment]
Same here. SOMETIMES buys champs , and selects a random augment. Doesnt do anything else. Doesnt place champs.

**Comment by akshualy** [comment]
> Same here. SOMETIMES buys champs , and selects a random augment. Doesnt do anything else. Doesnt place champs.

That sounds like the intended behavior. It's not super smart, it's just good enough for ~50% winrate in bot matches.
It'll buy the traits that are configured, buy XP, select the middle augment, and that's about it. You can install OCR to make it save up to 50 gold and hover around that value if you prefer.

There's some more sophisticated logic like item-placement in the planning, but it'll probably take a bit longer for that to become stable.

**Comment by NightRaven0** [comment]
I am having the same issue as this .... kinda

the bot runs the find match and accept and once its in game it only says what it wants to do and doesnt move mouse or anything, it only moves mouse when i have the script foucsed by Alt+tab to it but it still does not click to select anyway

**Comment by Kyrluckechuck** [comment]
@NightRaven0 odd to hear!

Can you let us know a few things:
- [ ] You are using the `1920x1080` resolution on the monitor the game is playing on for both the Windows desktop resolution & the in-game resolution
- [ ] The game is either in fullscreen or borderless windowed
- [ ] There is only one monitor, or the "primary" monitor is the left-most

And lastly, if you could attach the logs after this happens that would be very helpful!

**Comment by NightRaven0** [comment]
Yes, yes and yes 

also i have fixed it for some reason when i put false on the early ff line it broke it(?) i feel like its a me problem on this but now its up and running perfectly

**Comment by Kyrluckechuck** [comment]
Very odd! Do you mean `forfeit_early: false` in the config? 🤔 
That's how I've been running it for the last week or so, and yesterday for example I had it running for ~21h straight without issue and a 50% win rate 😕

**Comment by NightRaven0** [comment]
yea right now i have it like `forfeit_early:` thats it 

just empty and its working like yours 

also is there a way to make it pick up orbs? i am adding screenshots to capture as "traits"

**Comment by Kyrluckechuck** [comment]
Hmm, interesting that having `false` isn't working correctly, but glad to hear it _is working_ though! 🤔 

No, we do not currently have any orb logic, though that is a welcome feature request if you'd like to make one! 😅 

The "traits" logic unfortunately won't work, since that's a left-click and for orbs (pathing your avatar to them) it would require right-clicking. The lift on that isn't particularly difficult, but it's not just a drop-in replacement for the traits logic
