### ISSUE TITLE
Question: WQHD / 4K Support

### ISSUE THREAD

**Issue by BlackSiroGhost** [Kyrluckechuck/TFT-Bot#212]
Hi, just a question,
is there a plan to add WQHD (2K) or 4K Monitor Support?
Or is the mapping to difficult?

I know in the README is written to use FullHD (1920x1080) for best result.
I personaly use a 2K 16:9 monitor an am needed to scale my Leage down to 1080p.

Have a great day!

**Comment by Kyrluckechuck** [comment]
Hi @BlackSiroGhost !

You closed this, but just to answer the question that was asked; it's not currently supported (since we're currently doing image matching based on a pixel-to-pixel system), however if you have the skillset to, we'd be very open to any PRs 😄
