### ISSUE TITLE
Num lock Spam

### ISSUE THREAD

**Issue by Mysticql** [Kyrluckechuck/TFT-Bot#213]
Whenever it is being run the num lock on icon keeps flashing on screen every few seconds? Not sure what's causing this though.

**Comment by Mysticql** [comment]
Nevermind it seems like it was being caused by a typo in something

**Comment by Kyrluckechuck** [comment]
@Mysticql just to confirm, you're not still seeing this when using the bot, then? 😅

**Comment by Mysticql** [comment]
Yeah it stopped happening after I realized it was cause of a typo somewhere.
