### ISSUE TITLE
The bot does not buy champions

### ISSUE THREAD

**Issue by TogataMirioA2** [Kyrluckechuck/TFT-Bot#225]
it feels like the bot has no comp to build as he was building sorcery before but now it looks like he has no idea what to buy or build so he buys nothing .. other than that he does everything normally as it was before .. i reinstalled everything but had to face that same issue

**Comment by Kyrluckechuck** [comment]
To that end, I realize the latest release is quite old, so I've released a new update for those who aren't utilizing the `main` branch directly!

https://github.com/Kyrluckechuck/TFT-Bot/releases/tag/v0.11.13.19
