### ISSUE TITLE
bot no working in game 

### ISSUE THREAD

**Issue by boblolr** [Kyrluckechuck/TFT-Bot#235]
hey , the bot after starting the game wont do anything , not moving at all or buying , 

the game in on 1920x1080 , bordless ,

how can i fix that ?

**Comment by Kyrluckechuck** [comment]
Hi @boblolr , without more details that's going to be tough to debug!

Can you attach the logs from the bot? They will likely have a good indication as to why it's not working.

Do you have multiple monitors when running the bot?
