### ISSUE TITLE
50% of the time the bot loop breaks

### ISSUE THREAD

**Issue by 3RICtionYT** [Kyrluckechuck/TFT-Bot#248]
![image](https://github.com/Kyrluckechuck/TFT-Bot/assets/109010950/b86d6419-3fae-4ed6-8607-61ff456e923c)

^^ here is the photo of what my command terminal is sending me. any fix?

**Comment by 3RICtionYT** [comment]
btw ive lived with this issue for a while now. and my buddy also gets this error sometimes too

**Comment by 3RICtionYT** [comment]
also my league client would be closed, last game over, and signed out of my league account (but thats prob due to time)

**Comment by Kyrluckechuck** [comment]
Very odd, it looks like the client is failing to read the config, and failing to create one as well.
Can you attach the bot logs so we can attempt to debug it?

**Comment by 3RICtionYT** [comment]
> Very odd, it looks like the client is failing to read the config, and failing to create one as well. Can you attach the bot logs so we can attempt to debug it?

Howdo i find bot logs?

**Comment by Kyrluckechuck** [comment]
You should be able to locate the last run(s) with the naming convention `output\tft-bot-debug-TIMESTAMP.log` relative to where your files were being run, which based on your screenshot above I think would be in `C:\TFT-Bot-main\output`

**Comment by 3RICtionYT** [comment]
Found it: 
[tft-bot-debug-2024-03-23_03-51-55_794606.log](https://github.com/Kyrluckechuck/TFT-Bot/files/14734450/tft-bot-debug-2024-03-23_03-51-55_794606.log)

**Comment by akshualy** [comment]
It's trying to call the exe in the current directory. `update_riot_client_constants` is never called, unless the bot starts while league is closed. Can be fixed by adding
```py
riot_client_directory = system_helpers.determine_riot_client_install_location()
update_riot_client_constants(riot_client_directory)
```
to line 965 in tft.py.
