### ISSUE TITLE
left bot on over night after new bot version. bot now does this and opens a billion tabs.

### ISSUE THREAD

**Issue by 3RICtionYT** [Kyrluckechuck/TFT-Bot#254]
--- Removed image for user safety
[tft-bot-debug-2024-03-26_01-16-42_580959.log](https://github.com/Kyrluckechuck/TFT-Bot/files/14765084/tft-bot-debug-2024-03-26_01-16-42_580959.log)

**Comment by 3RICtionYT** [comment]
it seemed to also sign me out

**Comment by Kyrluckechuck** [comment]
So it looks like you were signed out, which League periodically randomly does, and the bot can't really do anything about that! 🤔
