### ISSUE TITLE
configuring config.yaml not saved

### ISSUE THREAD

**Issue by twkwow** [Kyrluckechuck/TFT-Bot#258]
I've saved some settings in the config.yaml, but when running the tft.py, it does not run the udpated config

**Comment by Kyrluckechuck** [comment]
What is the location of your `config.yaml`? 🤔 
Can you include the changes you made, as well as the logs from the bot?

**Comment by Kyrluckechuck** [comment]
On that note, I'd recommend you check out [Alune](https://github.com/TeamFightTacticsBots/Alune) as this project will now be archived
