### ISSUE TITLE
Clicking find match success: False

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [Kyrluckechuck/TFT-Bot#26]
The mouse goes to the right side of the monitor (as far as it goes)

`[1668513753] [MainThread] INFO     || Bot started, queuing up!
[1668513756] [MainThread] INFO     || TFT lobby detected, finding match
[1668513766] [MainThread] DEBUG    || Clicking find match success: False
[1668513778] [MainThread] DEBUG    || Clicking find match success: False
[1668513789] [MainThread] DEBUG    || Clicking find match success: False
[1668513801] [MainThread] DEBUG    || Clicking find match success: False`

**Comment by RomeoAlphaEkko** [comment]
tried activating "find match" to see if it would start after that by itself, 
it did not join the game

**Comment by Kyrluckechuck** [comment]
Very interesting that it would try to go off screen in order to click this image 🤔 

What screen resolution is your desktop set to, and which resolution for the League client?

Which version were you running when you tested this? If you haven't updated your local git copy, could you let me know what version you get when you type `git rev-parse HEAD`?

**Comment by RomeoAlphaEkko** [comment]
scaling 100%
2560x1440 screen resolution

league window size 1280x720

i downloaded the version as a zip today - ‎15. ‎November ‎2022, ‏‎11:49:59

**Comment by Kyrluckechuck** [comment]
Ah, so currently the bot (and everything about it) is designed to work with 1920x1080 due to how the scaling all works -- could you give that resolution a shot to see if that resolves it?

If so a feature request to work at 1440p would definitely make sense!

**Comment by RomeoAlphaEkko** [comment]
as an **update**, as there are new missions i wanted to revert to the other build

and went with pip install -r requirements.txt (theirs)

but the mouse went to the bottom right of the screen (as with this one) but it did not do so before trying this one out

so i went pip uninstall <packagename> for those listed in their requirements and then rerun pip install -r requirements.tx

not it finds and hits "find match" again

**Comment by Kyrluckechuck** [comment]
Very interesting -- is this not successfully recording your new missions in this build? Or was it just because it couldn't "find match" and such for you? 🤔

**Comment by RomeoAlphaEkko** [comment]
Find match, I assume the different version of one of the requirements is at fault

**Comment by Kyrluckechuck** [comment]
Ah gotcha -- so when you installed a fresh copy of the `requirements.txt` from this repo, it worked as expected?
