### ISSUE TITLE
README Overhaul

### ISSUE THREAD

**Issue by Kyrluckechuck** [Kyrluckechuck/TFT-Bot#28]
![](https://media.giphy.com/media/xT5LMpfqQyum08frRS/giphy.gif)

## Description / Request
The README is a bit out of date with new practices / major changes in how the client is expected to be used, would be good to modernize it!

- [x] Client should always be on left-most screen / main monitor (unconfirmed, relating to https://github.com/Kyrluckechuck/TFT-Bot/issues/26)
- [x] Usage with AIO executable
- [x] Usage with Python / dependencies (existing)
- [x] Clean up out of date information
- [ ] Add reference to disable Windows overlays (if enabled) via https://answers.microsoft.com/en-us/windows/forum/all/window-10-caps-lock-num-lock-key-desktop/483d79d9-5947-47e0-a7ef-2438d8215355 (#44)

Probably more things?

**Comment by uhpep** [comment]
how can i fix this issue mate? https://prnt.sc/j6LGEiG-cZyl
