### ISSUE TITLE
Client closes when I press start

### ISSUE THREAD

**Issue by Amaneki** [Kyrluckechuck/TFT-Bot#35]
After I press start on the popup the league client closes immediately. Used detergent13's version during the world's event so I don't know what could be causing this.

**Comment by Kyrluckechuck** [comment]
What command are you using to start the program?

Have you tried using the https://github.com/Kyrluckechuck/TFT-Bot/releases/tag/main-22741ea3 release?

Could you include the log file?

**Comment by Amaneki** [comment]
I'm using the py tft.py command to start the program.

I hadn't, but after trying it, it still closes the game and the program as well.

Log:
[TFT.Bot.log](https://github.com/Kyrluckechuck/TFT-Bot/files/10198928/TFT.Bot.log)

**Comment by Kyrluckechuck** [comment]
And after it closes it, it's failing to reopen it?

According to the logs, it's not detecting the client as running so it kills any process that matches the name and attempts to reopen it as a failsafe.

Do you have League installed in a non-default location by chance?

I had been putting off adding support for that since I hadn't heard of anyone doing it, but I can update that as a configuration if it's needed.

**Comment by Amaneki** [comment]
It does fail to reopen it.

I do have the game on a different drive, it could be that. I'll attempt installing it on my C: drive.

**Comment by Amaneki** [comment]
> 

Changing the game to the C: drive worked.
Funnily enough my mouse started to move to the right side of the screen but disabling my left monitor as said in #26 worked since we seemed to share the exact same problem (1440p main screen, 1080p left monitor).

**Comment by Kyrluckechuck** [comment]
Thanks for the info!

Regarding the issue of it having issues with your non-default install, I think I've addressed it with #38 , which I'll include in the next release -- if you give it a shot please let me know if it solves the problem (though no worries if you don't plan to re-install the client again)!

Very odd, but glad that the solution worked for you! Was there a particular step that it was doing on the other monitor, or was it most actions?
