### ISSUE TITLE
Please tell me how to do it

### ISSUE THREAD

**Issue by hyp0711** [Kyrluckechuck/TFT-Bot#41]
![123](https://user-images.githubusercontent.com/103652793/206871778-486fa9da-8f19-40b0-b7b4-d11728cc6bf9.PNG)
It only comes out like the picture above, but I don't know how to do it

**Comment by Kyrluckechuck** [comment]
Which version of python are you using?

If you're using Python 3.10, have you performed a `pip install -r requirements.txt`?

Would using the [latest release executable](https://github.com/Kyrluckechuck/TFT-Bot/releases/tag/main-5b159fe6) be better if you're not familiar with development?
