### ISSUE TITLE
Issue after at end of the match.

### ISSUE THREAD

**Issue by Domcaofficial** [Kyrluckechuck/TFT-Bot#64]
Hello after end of match, bot cant quit the game, there is repeatable this error.

![image](https://user-images.githubusercontent.com/122824194/212746478-71b112ce-70c6-4acf-91c6-85842a320c40.png)

Honestly i don´t know how to fix that error. resolution i have normal, which u wrote at installation steps.

**Comment by Kyrluckechuck** [comment]
Would you be able to screen cap this happening? It's likely the Exit Now button has changed and doesn't line up!

**Comment by Domcaofficial** [comment]
Can´t rn. I´m not atm at the pc. But Mouse move to exit button, and dont click. and it pops the same error as in logs.

**Comment by Kyrluckechuck** [comment]
I believe https://github.com/Kyrluckechuck/TFT-Bot/releases/tag/main-43fb6058 should address this
