### ISSUE TITLE
Autoqueue always on hyperoll 

### ISSUE THREAD

**Issue by Dazlian** [Kyrluckechuck/TFT-Bot#67]
So my question is about the auto queue it always goes to hyper roll it's the default mode on the launcher, is there some way to play normal only? thanks for sharing your work.

**Comment by Kyrluckechuck** [comment]
Hey @Dazlian!

I believe the client will auto-select the last mode selected, so what you'd need to do in that case is manually create a lobby of 'Normal', start the bot, and it should take it from there. After that game completes the auto queue should pick 'Normal' again by default!

Let me know if that resolves it for you!

**Comment by Dazlian** [comment]
I tried that multiple times but it doesn't change to normal, it may be something wrong with my client?

**Comment by Kyrluckechuck** [comment]
Dang, unfortunately looking at a bunch of threads on Reddit that 'feature' may just be broken and inconsistent...

I took a peek through all of my league config files to see if I saw any similarity, and I did see a line in `C:\Riot Games\League of Legends\Config\LCUAccountPreferences.yaml`:
```yaml
lol-tft:
    data:
        iconOverride: "summonerIcon"
        lastTftGameQueueId: 1090
```

You could try setting that value yourself and see if that last game queue id may happen to help? 🤔

**Comment by Dazlian** [comment]
That changed only to normal via the play button, the tft quick play keeps on Hyper Roll

**Comment by Kyrluckechuck** [comment]
This likely should have been resolved by https://github.com/Kyrluckechuck/TFT-Bot/pull/94 🙂
