### ISSUE TITLE
The program don't launch my game by itself

### ISSUE THREAD

**Issue by MollusqueNRV** [Kyrluckechuck/TFT-Bot#70]
Hi, i didn't even tried it in game but he don't want to find a match and accept it by itself, it just click on TFT on the client but that's all, i also have my league of legend file on another directory thant the default one so i created a bot-settings.ini with this text `[SETTINGS]
; Enable verbose output to console
Verbose = True
; For most scenarios I do not recommend enabling ForfeitEarly, since if you're botting pass EXP you get the most from staying in matches longer.
ForfeitEarly = False
; In most scenarios the below setting should not be required
OverrideInstallLocation = C:\Jeux\Riot Games\League of Legends`

And it still doesn't work, i'm a new user of python so please be kind with me, and thanks for helping

**Comment by MollusqueNRV** [comment]
Where can i get this debug log file ?

**Comment by Kyrluckechuck** [comment]
The log file located at `%APPDATA%/TFT Bot/TFT Bot.log` (running from release/executable) or `%APPDATA%/TFT Bot/tft.log` (running from Python source)

**Comment by Kyrluckechuck** [comment]
Hey there, any luck reproducing this and getting the log?

**Comment by Gadsee** [comment]
The client logic has been changed significantly, please re-open if this is still an issue for you!
