### ISSUE TITLE
Bot didn't auto find the game

### ISSUE THREAD

**Issue by haigamingP** [Kyrluckechuck/TFT-Bot#77]
When I start the bot, it launch the client and not thing happen it didn't find game. Is it a bug or something else?
[TFT.Bot.log](https://github.com/Kyrluckechuck/TFT-Bot/files/10713956/TFT.Bot.log)
![image](https://user-images.githubusercontent.com/103973664/218266293-0e8d8911-a768-43a1-88a4-c4e20d154c12.png)

**Comment by Kyrluckechuck** [comment]
If you start the bot while the League client is already open, do you still have this issue?

It appears that the bot is timing out or having a permissions issue when bringing the League process to the forefront, but I can't tell unfortunately if that means the process is dead or it just lacks permission to do so.

Is the account you're running this on a Windows Administrator or regular user?

**Comment by haigamingP** [comment]
If you start the bot while the League client is already open, do you still have this issue?
-Yes, I still have that issue
Is the account you're running this on a Windows Administrator or regular user?
-My account is a administrator
I have try use file source but it still have the same problem :')

**Comment by Kyrluckechuck** [comment]
Are you able to try installing League to the default location on the C:\ drive? I can't say for certain, but it appears it's having issues detecting the correct process / executable after launching it :thinking:

**Comment by Kyrluckechuck** [comment]
Any luck testing that out?

**Comment by Gadsee** [comment]
The client logic and in-game detection logic has been changed significantly, please re-open if this is still an issue for you!
