### ISSUE TITLE
ModuleNotFoundError: No module named 'keyboard'

### ISSUE THREAD

**Issue by eneszabun** [Kyrluckechuck/TFT-Bot#82]
![resim_2023-02-19_092151838](https://user-images.githubusercontent.com/93256908/219932519-b4209a9a-881f-4d2e-8a8a-2ad26b8f0fe0.png)
 I install python and pip but trying a run script it gave me this error. How can ı solve it?

**Comment by Kyrluckechuck** [comment]
Hello! If you're running this from source and not the pre-compiled executable, you need to ensure you have run `pip install -r requirements.txt` in the directory you're running `py tft.py`

**Comment by Jokiblack** [comment]
![image](https://user-images.githubusercontent.com/8556969/236251070-0bfb622a-9f0b-4c4c-8f1c-3f77f5497192.png)
nope... lose module

**Comment by Kyrluckechuck** [comment]
Hi @Jokiblack,

Can you ensure that `pip -V` is showing the same Python version as `python3 -V`?
