### ISSUE TITLE
No logic for Instant Feedback Report or Maintenance Popups

### ISSUE THREAD

**Issue by xChickens** [Kyrluckechuck/TFT-Bot#83]
I didn't want to make this until I got a screenshot of it happening but essentially the bot stopped working due to instant feedback report pop up and the maintenance pop up, as described above. The main reason why I'm posting now is just to bring awareness because I stupidly closed both immediately after seeing them when I could've gotten a perfect screenshot. (But I just realized I can just use Google for some images)

Essentially, I think usually on Tuesday nights before a patch, Riot will invalidate the login sessions of people as the servers go down for maintenance. This causes a pop up to appear giving an error message. Currently the bot will get stuck on this and not progress since the client does not close automatically. I actually can't remember the error message but here are some the examples the bot gets stuck on:

![image](https://user-images.githubusercontent.com/2402510/220538046-9131156f-70fd-4482-9e0c-fc0806d46f78.png)
![image](https://user-images.githubusercontent.com/2402510/220538245-2e3e7243-3055-4fe5-b5b1-5d668d83becd.png)
![image](https://user-images.githubusercontent.com/2402510/220538329-0e574ccf-51d2-4cb6-afdc-8847c816d7c6.png)

I'll try to get a screenshot tonight.

Another instance of the freezing up that I just encountered on logging in is that if you've recently played the game and reported someone and the dialog that states that "Your recent report of an unsportsmanlike player was verified and a penalty was issued." The bot is not able to handle this and ends up just freezing on the screen (mine got stuck on the 17th and I only just realized 😢).

This one is somewhat easy to find online:
![image](https://user-images.githubusercontent.com/2402510/220537302-cbf91f1c-eb94-48a7-b696-9f62c7f68cdf.png)

Lastly, just as a note, I use the pre-built executable that is given in releases. A common error that seems to pop up when the bot is glitched on something is something like `Pillow version ... needs to be installed`. I wish I wasn't stupid and got a copy of the logs, but I continually realized in hindsight that many things that would've been helpful in making this bug report.

Suggestions for fixing this is probably looking for these images, but I could also suggest a more general solution, in which, if after a certain time the bot has been stuck, the bot could do a force close of the client and reopen it. This could be something is toggled or default, but I think this could fix a lot of potential problems. Hope to hear your thoughts on it!

**Comment by Kyrluckechuck** [comment]
Hey @xChickens, thank you for this report! Sorry for the delay in responding.

I plan to include this in the next time I spend some time maintaining this, but I generally don't run the bot myself when there is no main League Event Pass, so I generally spend most of my time working on that during the event passes.

If you feel comfortable adding it in, I am receptive to incoming PRs! 😄 

> Lastly, just as a note, I use the pre-built executable that is given in releases. A common error that seems to pop up when the bot is glitched on something is something like Pillow version ... needs to be installed. I wish I wasn't stupid and got a copy of the logs, but I continually realized in hindsight that many things that would've been helpful in making this bug report

Hmm, that is very odd indeed! If you see this happen and are able to grab logs that would be much appreciated, but my best guess is that the temp directory somehow didn't extract correctly in the pre-built 🤔
