### ISSUE TITLE
Issue when trying to start enter a queue

### ISSUE THREAD

**Issue by MisterRath** [Kyrluckechuck/TFT-Bot#99]
I don't know if he can do it but when I'm in the client the bot is stuck when trying to detect if he s in the tft part and click on it but doesn t detect it while being in it so clicking on tft again and again
[tft-bot-debug-2023-03-30_23-35-44_145895.log](https://github.com/Kyrluckechuck/TFT-Bot/files/11116483/tft-bot-debug-2023-03-30_23-35-44_145895.log)

**Comment by MisterRath** [comment]
Can you explain if there is something to configure with the .exe in order to have a bot that can redo tft queue for hours

**Comment by Kyrluckechuck** [comment]
Would you mind sharing a screenshot of what your screen looks like when it sits idle like this?

According to the logs, it's attempting to find your "TFT" tab, however, no images are matching so it can't click it.

**Comment by MisterRath** [comment]
![Capture](https://user-images.githubusercontent.com/117355878/229144972-4df31663-9745-4cf2-acf4-309ed4ec220f.PNG)
Here it is ! it keeps clicking on tft but it doesn t detect that he s already in the tft menu

**Comment by MisterRath** [comment]
So i checked your codes but i can t find the selected tft tab in the constants, thinking that you forget to add them

**Comment by MisterRath** [comment]
SOLVED IT ! lmao i think that with the screen you can clearly see that my french client was not the right thing so i changed to english but i planned to make screenshot in french to make it viable in french (can send you the files if you want to make your program english and french versions

**Comment by Kyrluckechuck** [comment]
Ahhh that totally is it!

I looked at the screenshot a bit ago and after seeing the `TFT` tab selected just fine I totally skipped the rest, but that makes sense 😛 

Thanks for following up!
